apiVersion: v1
kind: ConfigMap
metadata:
  name: task-api-config
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskdb"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: task-api-secret
type: Opaque
stringData:
  DATABASE_USER: "taskuser"
  DATABASE_PASSWORD: "taskpass123"
